### ISSUE TITLE
Rules markdown button 

### ISSUE THREAD

**Issue by ghost** [Gojo-Bots/Gojo_Satoru#103]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Bro Your Repo Rules markdown button not supported add do it rules markdown feature 🎉

**Comment by iamgojoof6eyes** [comment]
Elaborate it more

**Comment by iamgojoof6eyes** [comment]
Done
