### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by TheFunkyFox** [Gojo-Bots/Gojo_Satoru#116]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Hello Sir, please Add /lock Url Feautures on Gojo this repo...... Kindly Feauture request.

**Comment by iamgojoof6eyes** [comment]
Thx for opening this issue. I have added lock url features in the bot it will available in next update

**Comment by iamgojoof6eyes** [comment]
@iamgojoof6eyes me hi hu vai
