### ISSUE TITLE
does not work 2.2.0

### ISSUE THREAD

**Issue by vlab97** [Gojo-Bots/Gojo_Satoru#162]
### Checklist

- [X] I am sure the error is coming from Gojo_Satoru's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I tried to run the code in different groups and channels and also in the bot's inbox and also changed the input value of the command

### Description

After updating to 2.2.0, the Bot generally stopped showing signs of life in telegram. does not respond to /start/help and other commands. there are no errors in the log

### Steps to reproduce

1 launch the bot
2 send any command to the bot

**Comment by iamgojoof6eyes** [comment]
Hmm working on it to fix it

**Comment by iamgojoof6eyes** [comment]
Will make it work. Thx for opening the issue and letting me know
