### ISSUE TITLE
Add support Regex

### ISSUE THREAD

**Issue by vlab97** [Gojo-Bots/Gojo_Satoru#165]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### Description

Add regular expression recognition to the filter and word blacklist functions. This will help you customize the bot better.

**Comment by iamgojoof6eyes** [comment]
It is already there. Please go through the repo or in detail of the bug before creating an issue

![Web capture_12-10-2023_85445_github com](https://github.com/Gojo-Bots/Gojo_Satoru/assets/91426868/41868763-c914-4a2a-a439-a4dfedb4dcef)
`regex for filters`

![Web capture_12-10-2023_85647_github com](https://github.com/Gojo-Bots/Gojo_Satoru/assets/91426868/729306a0-9f3a-4a74-adb0-ae1655bfee7f)
`regex for blacklist words`
