### ISSUE TITLE
fix this

### ISSUE THREAD

**Issue by UNNI12345YT** [Gojo-Bots/Gojo_Satoru#197]
### Checklist

- [X] I am sure the error is coming from Gojo_Satoru's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I tried to run the code in different groups and channels and also in the bot's inbox and also changed the input value of the command

### Description

tuple index out of range

### Steps to reproduce

tuple index out of range[(7172982933, '@Angelina345Bot', False), (6235483959, '@NATASHA345BOT', False), (7160423353, '@GOKU345BOT', True), (7072306256, '@KAKASHI_234_BOT', True), (7163286088, '@COBRA_MOVIE_BOT', False), (7164809399, '@KILIPOYA_BOY_BOT', False), (6171681404, '@UNNI_YT', False), (6200605339, 'COOLTECHdud')]

### Code example

```python
tuple index out of range[(7172982933, '@Angelina345Bot', False), (6235483959, '@NATASHA345BOT', False), (7160423353, '@GOKU345BOT', True), (7072306256, '@KAKASHI_234_BOT', True), (7163286088, '@COBRA_MOVIE_BOT', False), (7164809399, '@KILIPOYA_BOY_BOT', False), (6171681404, '@UNNI_YT', False), (6200605339, 'COOLTECHdud')]
```

### Logs

```shell
tuple index out of range[(7172982933, '@Angelina345Bot', False), (6235483959, '@NATASHA345BOT', False), (7160423353, '@GOKU345BOT', True), (7072306256, '@KAKASHI_234_BOT', True), (7163286088, '@COBRA_MOVIE_BOT', False), (7164809399, '@KILIPOYA_BOY_BOT', False), (6171681404, '@UNNI_YT', False), (6200605339, 'COOLTECHdud')]
```

**Comment by iamgojoof6eyes** [comment]
Please provide the necessary details.
